# -*- coding: utf-8 -*-
"""Market_basket_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tPxLRmEba6NbJDeXfmTFbgRt1ytR3k-B
"""

#Loading neccesary packages
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_csv('/content/Groceries_data.csv')

df.shape

df.head()

df['Member_number'].duplicated().sum() , df.shape , len(df['Member_number'].unique())

#we have 167 groceries
len(df['itemDescription'].unique())

basket = df.groupby('Member_number')['itemDescription'].agg(list).reset_index()
basket.head()

import seaborn as sns
sns.distplot(basket['itemDescription'].apply(len))

# We choose threshold 7 (Membors who purchase max items together), and for not occur null values
basket_data = basket[basket['itemDescription'].apply(len) == 7]

basket_data = basket_data['itemDescription'].apply(pd.Series)

basket_data.shape

enc_basket_data = pd.get_dummies(basket_data , dtype='int')

enc_basket_data.head()

"""# **Training Apriori model**"""

frequent_itemset = apriori(enc_basket_data , min_support=0.01 , use_colnames=True)

# We can see frequently purchased together
print(frequent_itemset)

rules = association_rules(frequent_itemset , metric='lift' , min_threshold=1)

rules

rules.sort_values('support' , ascending=False).head(10)

